# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f1afd30a96e388c22550c931b93c54def4d59b27459862f459e2e4834ca4bd21ff866e44dbda15c3f72298a371c50b89437b25938aeb52b0030a5742248c05

test:
  secret_key_base: 101f98448a8804d454da1dbd5592ba200112c96fa223ab0ef9343ec23354b4f33bb8f03d2f8c61710bf3fd0dff624cd5f174e451a41df548e7cac2cca2dd1c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
