require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Cms::CategoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cms::Category. As you add validations to Cms::Category, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Cms::CategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cms_categories as @cms_categories" do
      category = Cms::Category.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cms_categories)).to eq([category])
    end
  end

  describe "GET show" do
    it "assigns the requested cms_category as @cms_category" do
      category = Cms::Category.create! valid_attributes
      get :show, {:id => category.to_param}, valid_session
      expect(assigns(:cms_category)).to eq(category)
    end
  end

  describe "GET new" do
    it "assigns a new cms_category as @cms_category" do
      get :new, {}, valid_session
      expect(assigns(:cms_category)).to be_a_new(Cms::Category)
    end
  end

  describe "GET edit" do
    it "assigns the requested cms_category as @cms_category" do
      category = Cms::Category.create! valid_attributes
      get :edit, {:id => category.to_param}, valid_session
      expect(assigns(:cms_category)).to eq(category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cms::Category" do
        expect {
          post :create, {:cms_category => valid_attributes}, valid_session
        }.to change(Cms::Category, :count).by(1)
      end

      it "assigns a newly created cms_category as @cms_category" do
        post :create, {:cms_category => valid_attributes}, valid_session
        expect(assigns(:cms_category)).to be_a(Cms::Category)
        expect(assigns(:cms_category)).to be_persisted
      end

      it "redirects to the created cms_category" do
        post :create, {:cms_category => valid_attributes}, valid_session
        expect(response).to redirect_to(Cms::Category.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cms_category as @cms_category" do
        post :create, {:cms_category => invalid_attributes}, valid_session
        expect(assigns(:cms_category)).to be_a_new(Cms::Category)
      end

      it "re-renders the 'new' template" do
        post :create, {:cms_category => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cms_category" do
        category = Cms::Category.create! valid_attributes
        put :update, {:id => category.to_param, :cms_category => new_attributes}, valid_session
        category.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cms_category as @cms_category" do
        category = Cms::Category.create! valid_attributes
        put :update, {:id => category.to_param, :cms_category => valid_attributes}, valid_session
        expect(assigns(:cms_category)).to eq(category)
      end

      it "redirects to the cms_category" do
        category = Cms::Category.create! valid_attributes
        put :update, {:id => category.to_param, :cms_category => valid_attributes}, valid_session
        expect(response).to redirect_to(category)
      end
    end

    describe "with invalid params" do
      it "assigns the cms_category as @cms_category" do
        category = Cms::Category.create! valid_attributes
        put :update, {:id => category.to_param, :cms_category => invalid_attributes}, valid_session
        expect(assigns(:cms_category)).to eq(category)
      end

      it "re-renders the 'edit' template" do
        category = Cms::Category.create! valid_attributes
        put :update, {:id => category.to_param, :cms_category => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cms_category" do
      category = Cms::Category.create! valid_attributes
      expect {
        delete :destroy, {:id => category.to_param}, valid_session
      }.to change(Cms::Category, :count).by(-1)
    end

    it "redirects to the cms_categories list" do
      category = Cms::Category.create! valid_attributes
      delete :destroy, {:id => category.to_param}, valid_session
      expect(response).to redirect_to(cms_categories_url)
    end
  end

end
